<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
    <UserSecretsId>f932dda4-630d-4dc6-a04f-09bf9cfae534</UserSecretsId>
    <RootNamespace>elastic-web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Components\Pages\Search2.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Components\Pages\Search.razor.css" />
    <None Remove="Components\Pages\Results.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\Pages\Results.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\Pages\Search.razor.css" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="9.0.7" />
    <PackageReference Include="NEST" Version="7.17.5" />
  </ItemGroup>

</Project>
